#############################################################################
# Makefile for building: bin/synonym
# Generated by qmake (2.01a) (Qt 4.4.0) on: Sat Jul 19 18:31:35 2008
# Project:  synonym.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.4.0/bin/qmake -unix -o Makefile synonym.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_PHONON_LIB -DQT_SCRIPT_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.4.0/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtCore -I/usr/local/Trolltech/Qt-4.4.0/include/QtNetwork -I/usr/local/Trolltech/Qt-4.4.0/include/QtNetwork -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtGui -I/usr/local/Trolltech/Qt-4.4.0/include/QtXml -I/usr/local/Trolltech/Qt-4.4.0/include/QtXml -I/usr/local/Trolltech/Qt-4.4.0/include/QtSql -I/usr/local/Trolltech/Qt-4.4.0/include/QtSql -I/usr/local/Trolltech/Qt-4.4.0/include/QtSvg -I/usr/local/Trolltech/Qt-4.4.0/include/QtSvg -I/usr/local/Trolltech/Qt-4.4.0/include/QtScript -I/usr/local/Trolltech/Qt-4.4.0/include/QtScript -I/usr/local/Trolltech/Qt-4.4.0/include/phonon -I/usr/local/Trolltech/Qt-4.4.0/include/phonon -I/usr/local/Trolltech/Qt-4.4.0/include/QtWebKit -I/usr/local/Trolltech/Qt-4.4.0/include/QtWebKit -I/usr/local/Trolltech/Qt-4.4.0/include -I. -Isrc -Isrc/ui -Isrc/model -Isrc/audio -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/usr/local/Trolltech/Qt-4.4.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.4.0/lib -lQtWebKit -L/usr/local/Trolltech/Qt-4.4.0/lib -L/usr/X11R6/lib64 -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lphonon -lQtDBus -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -pthread -lQtScript -pthread -pthread -lQtSvg -pthread -pthread -pthread -pthread -pthread -pthread -lQtSql -pthread -pthread -lQtXml -pthread -pthread -lQtGui -lSM -lICE -pthread -pthread -lXrender -lXrandr -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -lpthread -ldl
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.4.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/model/wordgraph.cpp \
		src/model/partofspeechlistmodel.cpp \
		src/ui/graphnode.cpp \
		src/ui/graphedge.cpp \
		src/ui/graphscene.cpp \
		src/ui/graphcontroller.cpp \
		src/ui/graphwidget.cpp \
		src/ui/layout.cpp \
		src/ui/mainwindow.cpp \
		src/ui/partofspeechitemdelegate.cpp \
		src/ui/configdialog.cpp \
		src/main.cpp \
		src/model/relation.cpp \
		src/model/dbdataloader.cpp \
		src/audio/remoteaudiopronunciationloader.cpp \
		src/audio/scriptablesoundsource.cpp \
		src/audio/audiopronunciationloader.cpp \
		src/audio/localaudiopronunciationloader.cpp \
		src/audio/audiopronunciationloaderfactory.cpp \
		src/ui/tglayout.cpp \
		src/ui/forcedirectedlayout.cpp \
		src/ui/audioscriptpage.cpp moc_wordgraph.cpp \
		moc_partofspeechlistmodel.cpp \
		moc_graphscene.cpp \
		moc_graphwidget.cpp \
		moc_mainwindow.cpp \
		moc_partofspeechitemdelegate.cpp \
		moc_configdialog.cpp \
		moc_dbdataloader.cpp \
		moc_remoteaudiopronunciationloader.cpp \
		moc_scriptablesoundsource.cpp \
		moc_audiopronunciationloader.cpp \
		moc_localaudiopronunciationloader.cpp \
		moc_soundsource.cpp \
		moc_tglayout.cpp \
		moc_forcedirectedlayout.cpp \
		moc_audioscriptpage.cpp \
		qrc_synonym.cpp
OBJECTS       = wordgraph.o \
		partofspeechlistmodel.o \
		graphnode.o \
		graphedge.o \
		graphscene.o \
		graphcontroller.o \
		graphwidget.o \
		layout.o \
		mainwindow.o \
		partofspeechitemdelegate.o \
		configdialog.o \
		main.o \
		relation.o \
		dbdataloader.o \
		remoteaudiopronunciationloader.o \
		scriptablesoundsource.o \
		audiopronunciationloader.o \
		localaudiopronunciationloader.o \
		audiopronunciationloaderfactory.o \
		tglayout.o \
		forcedirectedlayout.o \
		audioscriptpage.o \
		moc_wordgraph.o \
		moc_partofspeechlistmodel.o \
		moc_graphscene.o \
		moc_graphwidget.o \
		moc_mainwindow.o \
		moc_partofspeechitemdelegate.o \
		moc_configdialog.o \
		moc_dbdataloader.o \
		moc_remoteaudiopronunciationloader.o \
		moc_scriptablesoundsource.o \
		moc_audiopronunciationloader.o \
		moc_localaudiopronunciationloader.o \
		moc_soundsource.o \
		moc_tglayout.o \
		moc_forcedirectedlayout.o \
		moc_audioscriptpage.o \
		qrc_synonym.o
DIST          = /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		synonym.pro
QMAKE_TARGET  = synonym
DESTDIR       = bin/
TARGET        = bin/synonym

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_displayconfig.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: synonym.pro  /usr/local/Trolltech/Qt-4.4.0/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtWebKit.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtNetwork.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libphonon.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtDBus.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtScript.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtSvg.prl \
		/usr/local/Trolltech/Qt-4.4.0/lib/libQtSql.prl
	$(QMAKE) -unix -o Makefile synonym.pro
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.4.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtWebKit.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtNetwork.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libphonon.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtDBus.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtScript.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtSvg.prl:
/usr/local/Trolltech/Qt-4.4.0/lib/libQtSql.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile synonym.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/synonym1.0.0 || $(MKDIR) .tmp/synonym1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/synonym1.0.0/ && $(COPY_FILE) --parents src/model/wordgraph.h src/model/partofspeechlistmodel.h src/ui/graphnode.h src/ui/graphedge.h src/ui/graphscene.h src/ui/graphcontroller.h src/ui/graphwidget.h src/ui/mainwindow.h src/ui/partofspeechitemdelegate.h src/ui/layout.h src/ui/configdialog.h src/model/graphalgorithms.h src/model/wordnetutil.h src/model/iworddataloader.h src/model/relation.h src/model/dbdataloader.h src/audio/remoteaudiopronunciationloader.h src/audio/scriptablesoundsource.h src/audio/audiopronunciationloader.h src/audio/localaudiopronunciationloader.h src/audio/audiopronunciationloaderfactory.h src/audio/soundsource.h src/ui/tglayout.h src/ui/forcedirectedlayout.h src/ui/audioscriptpage.h .tmp/synonym1.0.0/ && $(COPY_FILE) --parents src/synonym.qrc .tmp/synonym1.0.0/ && $(COPY_FILE) --parents src/model/wordgraph.cpp src/model/partofspeechlistmodel.cpp src/ui/graphnode.cpp src/ui/graphedge.cpp src/ui/graphscene.cpp src/ui/graphcontroller.cpp src/ui/graphwidget.cpp src/ui/layout.cpp src/ui/mainwindow.cpp src/ui/partofspeechitemdelegate.cpp src/ui/configdialog.cpp src/main.cpp src/model/relation.cpp src/model/dbdataloader.cpp src/audio/remoteaudiopronunciationloader.cpp src/audio/scriptablesoundsource.cpp src/audio/audiopronunciationloader.cpp src/audio/localaudiopronunciationloader.cpp src/audio/audiopronunciationloaderfactory.cpp src/ui/tglayout.cpp src/ui/forcedirectedlayout.cpp src/ui/audioscriptpage.cpp .tmp/synonym1.0.0/ && $(COPY_FILE) --parents src/ui/displayconfig.ui .tmp/synonym1.0.0/ && (cd `dirname .tmp/synonym1.0.0` && $(TAR) synonym1.0.0.tar synonym1.0.0 && $(COMPRESS) synonym1.0.0.tar) && $(MOVE) `dirname .tmp/synonym1.0.0`/synonym1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/synonym1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_wordgraph.cpp moc_partofspeechlistmodel.cpp moc_graphscene.cpp moc_graphcontroller.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_partofspeechitemdelegate.cpp moc_configdialog.cpp moc_dbdataloader.cpp moc_remoteaudiopronunciationloader.cpp moc_scriptablesoundsource.cpp moc_audiopronunciationloader.cpp moc_localaudiopronunciationloader.cpp moc_soundsource.cpp moc_tglayout.cpp moc_forcedirectedlayout.cpp moc_audioscriptpage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_wordgraph.cpp moc_partofspeechlistmodel.cpp moc_graphscene.cpp moc_graphcontroller.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_partofspeechitemdelegate.cpp moc_configdialog.cpp moc_dbdataloader.cpp moc_remoteaudiopronunciationloader.cpp moc_scriptablesoundsource.cpp moc_audiopronunciationloader.cpp moc_localaudiopronunciationloader.cpp moc_soundsource.cpp moc_tglayout.cpp moc_forcedirectedlayout.cpp moc_audioscriptpage.cpp
moc_wordgraph.cpp: src/model/graphalgorithms.h \
		src/model/wordgraph.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/model/wordgraph.h -o moc_wordgraph.cpp

moc_partofspeechlistmodel.cpp: src/model/relation.h \
		src/model/wordgraph.h \
		src/model/graphalgorithms.h \
		src/model/partofspeechlistmodel.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/model/partofspeechlistmodel.h -o moc_partofspeechlistmodel.cpp

moc_graphscene.cpp: src/ui/graphscene.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/graphscene.h -o moc_graphscene.cpp

moc_graphcontroller.cpp: src/ui/graphcontroller.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/graphcontroller.h -o moc_graphcontroller.cpp

moc_graphwidget.cpp: src/ui/graphwidget.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/graphwidget.h -o moc_graphwidget.cpp

moc_mainwindow.cpp: src/ui/mainwindow.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/mainwindow.h -o moc_mainwindow.cpp

moc_partofspeechitemdelegate.cpp: src/ui/partofspeechitemdelegate.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/partofspeechitemdelegate.h -o moc_partofspeechitemdelegate.cpp

moc_configdialog.cpp: ui_displayconfig.h \
		src/ui/configdialog.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/configdialog.h -o moc_configdialog.cpp

moc_dbdataloader.cpp: src/model/relation.h \
		src/model/dbdataloader.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/model/dbdataloader.h -o moc_dbdataloader.cpp

moc_remoteaudiopronunciationloader.cpp: src/audio/audiopronunciationloader.h \
		src/audio/soundsource.h \
		src/audio/remoteaudiopronunciationloader.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/audio/remoteaudiopronunciationloader.h -o moc_remoteaudiopronunciationloader.cpp

moc_scriptablesoundsource.cpp: src/audio/soundsource.h \
		src/audio/scriptablesoundsource.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/audio/scriptablesoundsource.h -o moc_scriptablesoundsource.cpp

moc_audiopronunciationloader.cpp: src/audio/audiopronunciationloader.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/audio/audiopronunciationloader.h -o moc_audiopronunciationloader.cpp

moc_localaudiopronunciationloader.cpp: src/audio/audiopronunciationloader.h \
		src/audio/localaudiopronunciationloader.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/audio/localaudiopronunciationloader.h -o moc_localaudiopronunciationloader.cpp

moc_soundsource.cpp: src/audio/soundsource.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/audio/soundsource.h -o moc_soundsource.cpp

moc_tglayout.cpp: src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h \
		src/ui/tglayout.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/tglayout.h -o moc_tglayout.cpp

moc_forcedirectedlayout.cpp: src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h \
		src/ui/forcedirectedlayout.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/forcedirectedlayout.h -o moc_forcedirectedlayout.cpp

moc_audioscriptpage.cpp: src/ui/configdialog.h \
		ui_displayconfig.h \
		src/ui/audioscriptpage.h
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/audioscriptpage.h -o moc_audioscriptpage.cpp

compiler_rcc_make_all: qrc_synonym.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_synonym.cpp
qrc_synonym.cpp: src/synonym.qrc \
		src/resources/Sound-icon.svg \
		src/resources/synonymicon3.png
	/usr/local/Trolltech/Qt-4.4.0/bin/rcc -name synonym src/synonym.qrc -o qrc_synonym.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: mainwindow.moc
compiler_moc_source_clean:
	-$(DEL_FILE) mainwindow.moc
mainwindow.moc: src/ui/mainwindow.h \
		src/ui/graphwidget.h \
		src/ui/graphscene.h \
		src/ui/graphcontroller.h \
		src/ui/partofspeechitemdelegate.h \
		src/ui/configdialog.h \
		ui_displayconfig.h \
		src/ui/tglayout.h \
		src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/mainwindow.cpp
	/usr/local/Trolltech/Qt-4.4.0/bin/moc $(DEFINES) $(INCPATH) src/ui/mainwindow.cpp -o mainwindow.moc

compiler_uic_make_all: ui_displayconfig.h
compiler_uic_clean:
	-$(DEL_FILE) ui_displayconfig.h
ui_displayconfig.h: src/ui/displayconfig.ui
	/usr/local/Trolltech/Qt-4.4.0/bin/uic src/ui/displayconfig.ui -o ui_displayconfig.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

wordgraph.o: src/model/wordgraph.cpp src/model/wordgraph.h \
		src/model/graphalgorithms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wordgraph.o src/model/wordgraph.cpp

partofspeechlistmodel.o: src/model/partofspeechlistmodel.cpp src/model/partofspeechlistmodel.h \
		src/model/relation.h \
		src/model/wordgraph.h \
		src/model/graphalgorithms.h \
		src/model/wordnetutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partofspeechlistmodel.o src/model/partofspeechlistmodel.cpp

graphnode.o: src/ui/graphnode.cpp src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphnode.o src/ui/graphnode.cpp

graphedge.o: src/ui/graphedge.cpp src/ui/graphedge.h \
		src/ui/graphnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphedge.o src/ui/graphedge.cpp

graphscene.o: src/ui/graphscene.cpp src/ui/graphscene.h \
		src/ui/graphedge.h \
		src/ui/graphnode.h \
		src/ui/tglayout.h \
		src/ui/layout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphscene.o src/ui/graphscene.cpp

graphcontroller.o: src/ui/graphcontroller.cpp src/ui/graphcontroller.h \
		src/ui/graphscene.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		moc_graphcontroller.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphcontroller.o src/ui/graphcontroller.cpp

graphwidget.o: src/ui/graphwidget.cpp src/ui/graphwidget.h \
		src/ui/graphscene.h \
		src/ui/graphcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o src/ui/graphwidget.cpp

layout.o: src/ui/layout.cpp src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layout.o src/ui/layout.cpp

mainwindow.o: src/ui/mainwindow.cpp src/ui/mainwindow.h \
		src/ui/graphwidget.h \
		src/ui/graphscene.h \
		src/ui/graphcontroller.h \
		src/ui/partofspeechitemdelegate.h \
		src/ui/configdialog.h \
		ui_displayconfig.h \
		src/ui/tglayout.h \
		src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		mainwindow.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/ui/mainwindow.cpp

partofspeechitemdelegate.o: src/ui/partofspeechitemdelegate.cpp src/ui/partofspeechitemdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partofspeechitemdelegate.o src/ui/partofspeechitemdelegate.cpp

configdialog.o: src/ui/configdialog.cpp src/ui/configdialog.h \
		ui_displayconfig.h \
		src/ui/graphscene.h \
		src/ui/tglayout.h \
		src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphcontroller.h \
		src/ui/audioscriptpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o src/ui/configdialog.cpp

main.o: src/main.cpp src/ui/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

relation.o: src/model/relation.cpp src/model/relation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relation.o src/model/relation.cpp

dbdataloader.o: src/model/dbdataloader.cpp src/model/dbdataloader.h \
		src/model/relation.h \
		src/model/wordgraph.h \
		src/model/graphalgorithms.h \
		src/model/wordnetutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbdataloader.o src/model/dbdataloader.cpp

remoteaudiopronunciationloader.o: src/audio/remoteaudiopronunciationloader.cpp src/audio/remoteaudiopronunciationloader.h \
		src/audio/audiopronunciationloader.h \
		src/audio/soundsource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o remoteaudiopronunciationloader.o src/audio/remoteaudiopronunciationloader.cpp

scriptablesoundsource.o: src/audio/scriptablesoundsource.cpp src/audio/scriptablesoundsource.h \
		src/audio/soundsource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scriptablesoundsource.o src/audio/scriptablesoundsource.cpp

audiopronunciationloader.o: src/audio/audiopronunciationloader.cpp src/audio/audiopronunciationloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiopronunciationloader.o src/audio/audiopronunciationloader.cpp

localaudiopronunciationloader.o: src/audio/localaudiopronunciationloader.cpp src/audio/localaudiopronunciationloader.h \
		src/audio/audiopronunciationloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localaudiopronunciationloader.o src/audio/localaudiopronunciationloader.cpp

audiopronunciationloaderfactory.o: src/audio/audiopronunciationloaderfactory.cpp src/audio/audiopronunciationloaderfactory.h \
		src/audio/remoteaudiopronunciationloader.h \
		src/audio/audiopronunciationloader.h \
		src/audio/soundsource.h \
		src/audio/scriptablesoundsource.h \
		src/audio/localaudiopronunciationloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiopronunciationloaderfactory.o src/audio/audiopronunciationloaderfactory.cpp

tglayout.o: src/ui/tglayout.cpp src/ui/tglayout.h \
		src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tglayout.o src/ui/tglayout.cpp

forcedirectedlayout.o: src/ui/forcedirectedlayout.cpp src/ui/forcedirectedlayout.h \
		src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forcedirectedlayout.o src/ui/forcedirectedlayout.cpp

audioscriptpage.o: src/ui/audioscriptpage.cpp src/ui/audioscriptpage.h \
		src/ui/configdialog.h \
		ui_displayconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioscriptpage.o src/ui/audioscriptpage.cpp

moc_wordgraph.o: moc_wordgraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wordgraph.o moc_wordgraph.cpp

moc_partofspeechlistmodel.o: moc_partofspeechlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partofspeechlistmodel.o moc_partofspeechlistmodel.cpp

moc_graphscene.o: moc_graphscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphscene.o moc_graphscene.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_partofspeechitemdelegate.o: moc_partofspeechitemdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partofspeechitemdelegate.o moc_partofspeechitemdelegate.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_dbdataloader.o: moc_dbdataloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbdataloader.o moc_dbdataloader.cpp

moc_remoteaudiopronunciationloader.o: moc_remoteaudiopronunciationloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_remoteaudiopronunciationloader.o moc_remoteaudiopronunciationloader.cpp

moc_scriptablesoundsource.o: moc_scriptablesoundsource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scriptablesoundsource.o moc_scriptablesoundsource.cpp

moc_audiopronunciationloader.o: moc_audiopronunciationloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audiopronunciationloader.o moc_audiopronunciationloader.cpp

moc_localaudiopronunciationloader.o: moc_localaudiopronunciationloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localaudiopronunciationloader.o moc_localaudiopronunciationloader.cpp

moc_soundsource.o: moc_soundsource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundsource.o moc_soundsource.cpp

moc_tglayout.o: moc_tglayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tglayout.o moc_tglayout.cpp

moc_forcedirectedlayout.o: moc_forcedirectedlayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_forcedirectedlayout.o moc_forcedirectedlayout.cpp

moc_audioscriptpage.o: moc_audioscriptpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audioscriptpage.o moc_audioscriptpage.cpp

qrc_synonym.o: qrc_synonym.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_synonym.o qrc_synonym.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

