#############################################################################
# Makefile for building: bin/synonym
# Generated by qmake (2.01a) (Qt 4.3.1) on: Thu Aug 23 22:35:17 2007
# Project:  synonym.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.3.1/bin/qmake -unix -o Makefile synonym.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.3.1/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.3.1/include/QtCore -I/usr/local/Trolltech/Qt-4.3.1/include/QtCore -I/usr/local/Trolltech/Qt-4.3.1/include/QtNetwork -I/usr/local/Trolltech/Qt-4.3.1/include/QtNetwork -I/usr/local/Trolltech/Qt-4.3.1/include/QtGui -I/usr/local/Trolltech/Qt-4.3.1/include/QtGui -I/usr/local/Trolltech/Qt-4.3.1/include/QtXml -I/usr/local/Trolltech/Qt-4.3.1/include/QtXml -I/usr/local/Trolltech/Qt-4.3.1/include/QtSvg -I/usr/local/Trolltech/Qt-4.3.1/include/QtSvg -I/usr/local/Trolltech/Qt-4.3.1/include -I. -Isrc -Isrc/ui -Isrc/model -Isrc/sound -I/usr/include/kde -I/usr/local/WordNet-3.0/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/usr/local/Trolltech/Qt-4.3.1/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.3.1/lib -L/usr/local/WordNet-3.0/lib -lWN -lQtSvg -L/usr/local/Trolltech/Qt-4.3.1/lib -L/usr/X11R6/lib64 -lQtXml -lQtGui -lSM -lICE -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.3.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/model/worddatagraph.cpp \
		src/model/edge.cpp \
		src/model/node.cpp \
		src/model/worddataloader.cpp \
		src/model/partofspeechlistmodel.cpp \
		src/ui/graphnode.cpp \
		src/ui/graphedge.cpp \
		src/ui/graphscene.cpp \
		src/ui/graphcontroller.cpp \
		src/ui/graphwidget.cpp \
		src/ui/layout.cpp \
		src/main.cpp \
		src/ui/mainwindow.cpp \
		src/ui/partofspeechitemdelegate.cpp \
		src/ui/wordsoundholder.cpp \
		src/ui/wordsoundimpl.cpp \
		src/sound/pronunciationsoundholder.cpp \
		src/sound/pronunciationsoundfactoryimpl.cpp \
		src/sound/player.cpp moc_worddatagraph.cpp \
		moc_node.cpp \
		moc_worddataloader.cpp \
		moc_partofspeechlistmodel.cpp \
		moc_graphscene.cpp \
		moc_graphwidget.cpp \
		moc_mainwindow.cpp \
		moc_partofspeechitemdelegate.cpp \
		moc_wordsoundholder.cpp \
		moc_wordsoundimpl.cpp \
		moc_layout.cpp \
		moc_pronunciationsoundholder.cpp \
		moc_pronunciationsoundfactoryimpl.cpp \
		moc_player.cpp
OBJECTS       = worddatagraph.o \
		edge.o \
		node.o \
		worddataloader.o \
		partofspeechlistmodel.o \
		graphnode.o \
		graphedge.o \
		graphscene.o \
		graphcontroller.o \
		graphwidget.o \
		layout.o \
		main.o \
		mainwindow.o \
		partofspeechitemdelegate.o \
		wordsoundholder.o \
		wordsoundimpl.o \
		pronunciationsoundholder.o \
		pronunciationsoundfactoryimpl.o \
		player.o \
		moc_worddatagraph.o \
		moc_node.o \
		moc_worddataloader.o \
		moc_partofspeechlistmodel.o \
		moc_graphscene.o \
		moc_graphwidget.o \
		moc_mainwindow.o \
		moc_partofspeechitemdelegate.o \
		moc_wordsoundholder.o \
		moc_wordsoundimpl.o \
		moc_layout.o \
		moc_pronunciationsoundholder.o \
		moc_pronunciationsoundfactoryimpl.o \
		moc_player.o
DIST          = /usr/local/Trolltech/Qt-4.3.1/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/lex.prf \
		synonym.pro
QMAKE_TARGET  = synonym
DESTDIR       = bin/
TARGET        = bin/synonym

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: synonym.pro  /usr/local/Trolltech/Qt-4.3.1/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.3.1/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.3.1/lib/libQtSvg.prl \
		/usr/local/Trolltech/Qt-4.3.1/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-4.3.1/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.3.1/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.3.1/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile synonym.pro
/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.3.1/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.3.1/lib/libQtSvg.prl:
/usr/local/Trolltech/Qt-4.3.1/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-4.3.1/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.3.1/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.3.1/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile synonym.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/synonym1.0.0 || $(MKDIR) .tmp/synonym1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/synonym1.0.0/ && $(COPY_FILE) --parents src/model/worddatagraph.h src/model/edge.h src/model/node.h src/model/worddataloader.h src/model/partofspeechlistmodel.h src/ui/graphnode.h src/ui/graphedge.h src/ui/graphscene.h src/ui/graphcontroller.h src/ui/graphwidget.h src/ui/mainwindow.h src/ui/partofspeechitemdelegate.h src/ui/wordsoundinterface.h src/ui/wordsoundholder.h src/ui/wordsoundimpl.h src/ui/layout.h src/sound/pronunciationsoundfactory.h src/sound/pronunciationsoundholder.h src/sound/pronunciationsoundfactoryimpl.h src/sound/player.h .tmp/synonym1.0.0/ && $(COPY_FILE) --parents src/model/worddatagraph.cpp src/model/edge.cpp src/model/node.cpp src/model/worddataloader.cpp src/model/partofspeechlistmodel.cpp src/ui/graphnode.cpp src/ui/graphedge.cpp src/ui/graphscene.cpp src/ui/graphcontroller.cpp src/ui/graphwidget.cpp src/ui/layout.cpp src/main.cpp src/ui/mainwindow.cpp src/ui/partofspeechitemdelegate.cpp src/ui/wordsoundholder.cpp src/ui/wordsoundimpl.cpp src/sound/pronunciationsoundholder.cpp src/sound/pronunciationsoundfactoryimpl.cpp src/sound/player.cpp .tmp/synonym1.0.0/ && (cd `dirname .tmp/synonym1.0.0` && $(TAR) synonym1.0.0.tar synonym1.0.0 && $(COMPRESS) synonym1.0.0.tar) && $(MOVE) `dirname .tmp/synonym1.0.0`/synonym1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/synonym1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_worddatagraph.cpp moc_node.cpp moc_worddataloader.cpp moc_partofspeechlistmodel.cpp moc_graphscene.cpp moc_graphcontroller.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_partofspeechitemdelegate.cpp moc_wordsoundholder.cpp moc_wordsoundimpl.cpp moc_layout.cpp moc_pronunciationsoundholder.cpp moc_pronunciationsoundfactoryimpl.cpp moc_player.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_worddatagraph.cpp moc_node.cpp moc_worddataloader.cpp moc_partofspeechlistmodel.cpp moc_graphscene.cpp moc_graphcontroller.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_partofspeechitemdelegate.cpp moc_wordsoundholder.cpp moc_wordsoundimpl.cpp moc_layout.cpp moc_pronunciationsoundholder.cpp moc_pronunciationsoundfactoryimpl.cpp moc_player.cpp
moc_worddatagraph.cpp: src/model/node.h \
		src/model/edge.h \
		src/model/worddatagraph.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/model/worddatagraph.h -o moc_worddatagraph.cpp

moc_node.cpp: src/model/node.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/model/node.h -o moc_node.cpp

moc_worddataloader.cpp: src/model/worddataloader.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/model/worddataloader.h -o moc_worddataloader.cpp

moc_partofspeechlistmodel.cpp: src/model/node.h \
		src/model/partofspeechlistmodel.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/model/partofspeechlistmodel.h -o moc_partofspeechlistmodel.cpp

moc_graphscene.cpp: src/ui/graphscene.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/graphscene.h -o moc_graphscene.cpp

moc_graphcontroller.cpp: src/ui/graphcontroller.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/graphcontroller.h -o moc_graphcontroller.cpp

moc_graphwidget.cpp: src/ui/graphwidget.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/graphwidget.h -o moc_graphwidget.cpp

moc_mainwindow.cpp: src/ui/mainwindow.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/mainwindow.h -o moc_mainwindow.cpp

moc_partofspeechitemdelegate.cpp: src/ui/partofspeechitemdelegate.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/partofspeechitemdelegate.h -o moc_partofspeechitemdelegate.cpp

moc_wordsoundholder.cpp: src/ui/wordsoundholder.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/wordsoundholder.h -o moc_wordsoundholder.cpp

moc_wordsoundimpl.cpp: src/ui/wordsoundinterface.h \
		src/ui/wordsoundholder.h \
		src/ui/wordsoundimpl.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/wordsoundimpl.h -o moc_wordsoundimpl.cpp

moc_layout.cpp: src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h \
		src/ui/layout.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/ui/layout.h -o moc_layout.cpp

moc_pronunciationsoundholder.cpp: src/sound/pronunciationsoundholder.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/sound/pronunciationsoundholder.h -o moc_pronunciationsoundholder.cpp

moc_pronunciationsoundfactoryimpl.cpp: src/sound/pronunciationsoundfactory.h \
		src/sound/pronunciationsoundholder.h \
		src/sound/pronunciationsoundfactoryimpl.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/sound/pronunciationsoundfactoryimpl.h -o moc_pronunciationsoundfactoryimpl.cpp

moc_player.cpp: src/sound/player.h
	/usr/local/Trolltech/Qt-4.3.1/bin/moc $(DEFINES) $(INCPATH) src/sound/player.h -o moc_player.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

worddatagraph.o: src/model/worddatagraph.cpp src/model/worddatagraph.h \
		src/model/node.h \
		src/model/edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worddatagraph.o src/model/worddatagraph.cpp

edge.o: src/model/edge.cpp src/model/edge.h \
		src/model/node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o src/model/edge.cpp

node.o: src/model/node.cpp src/model/node.h \
		src/model/edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o src/model/node.cpp

worddataloader.o: src/model/worddataloader.cpp src/model/worddataloader.h \
		src/model/worddatagraph.h \
		src/model/node.h \
		src/model/edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worddataloader.o src/model/worddataloader.cpp

partofspeechlistmodel.o: src/model/partofspeechlistmodel.cpp src/model/partofspeechlistmodel.h \
		src/model/node.h \
		src/model/worddatagraph.h \
		src/model/edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partofspeechlistmodel.o src/model/partofspeechlistmodel.cpp

graphnode.o: src/ui/graphnode.cpp src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphnode.o src/ui/graphnode.cpp

graphedge.o: src/ui/graphedge.cpp src/ui/graphedge.h \
		src/ui/graphnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphedge.o src/ui/graphedge.cpp

graphscene.o: src/ui/graphscene.cpp src/ui/graphscene.h \
		src/ui/graphedge.h \
		src/ui/graphnode.h \
		src/ui/layout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphscene.o src/ui/graphscene.cpp

graphcontroller.o: src/ui/graphcontroller.cpp src/ui/graphcontroller.h \
		src/ui/graphscene.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		moc_graphcontroller.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphcontroller.o src/ui/graphcontroller.cpp

graphwidget.o: src/ui/graphwidget.cpp src/ui/graphwidget.h \
		src/ui/graphscene.h \
		src/ui/graphcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o src/ui/graphwidget.cpp

layout.o: src/ui/layout.cpp src/ui/layout.h \
		src/ui/graphnode.h \
		src/ui/graphedge.h \
		src/ui/graphscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o layout.o src/ui/layout.cpp

main.o: src/main.cpp src/ui/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/ui/mainwindow.cpp src/ui/mainwindow.h \
		src/ui/graphwidget.h \
		src/ui/graphscene.h \
		src/ui/graphcontroller.h \
		src/ui/partofspeechitemdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/ui/mainwindow.cpp

partofspeechitemdelegate.o: src/ui/partofspeechitemdelegate.cpp src/ui/partofspeechitemdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partofspeechitemdelegate.o src/ui/partofspeechitemdelegate.cpp

wordsoundholder.o: src/ui/wordsoundholder.cpp src/ui/wordsoundholder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wordsoundholder.o src/ui/wordsoundholder.cpp

wordsoundimpl.o: src/ui/wordsoundimpl.cpp src/ui/wordsoundimpl.h \
		src/ui/wordsoundinterface.h \
		src/ui/wordsoundholder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wordsoundimpl.o src/ui/wordsoundimpl.cpp

pronunciationsoundholder.o: src/sound/pronunciationsoundholder.cpp src/sound/pronunciationsoundholder.h \
		src/sound/pronunciationsoundfactory.h \
		src/sound/pronunciationsoundfactoryimpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pronunciationsoundholder.o src/sound/pronunciationsoundholder.cpp

pronunciationsoundfactoryimpl.o: src/sound/pronunciationsoundfactoryimpl.cpp src/sound/pronunciationsoundfactoryimpl.h \
		src/sound/pronunciationsoundfactory.h \
		src/sound/pronunciationsoundholder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pronunciationsoundfactoryimpl.o src/sound/pronunciationsoundfactoryimpl.cpp

player.o: src/sound/player.cpp src/sound/player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o src/sound/player.cpp

moc_worddatagraph.o: moc_worddatagraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worddatagraph.o moc_worddatagraph.cpp

moc_node.o: moc_node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_node.o moc_node.cpp

moc_worddataloader.o: moc_worddataloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worddataloader.o moc_worddataloader.cpp

moc_partofspeechlistmodel.o: moc_partofspeechlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partofspeechlistmodel.o moc_partofspeechlistmodel.cpp

moc_graphscene.o: moc_graphscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphscene.o moc_graphscene.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_partofspeechitemdelegate.o: moc_partofspeechitemdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partofspeechitemdelegate.o moc_partofspeechitemdelegate.cpp

moc_wordsoundholder.o: moc_wordsoundholder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wordsoundholder.o moc_wordsoundholder.cpp

moc_wordsoundimpl.o: moc_wordsoundimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wordsoundimpl.o moc_wordsoundimpl.cpp

moc_layout.o: moc_layout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_layout.o moc_layout.cpp

moc_pronunciationsoundholder.o: moc_pronunciationsoundholder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pronunciationsoundholder.o moc_pronunciationsoundholder.cpp

moc_pronunciationsoundfactoryimpl.o: moc_pronunciationsoundfactoryimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pronunciationsoundfactoryimpl.o moc_pronunciationsoundfactoryimpl.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

